openapi: 3.0.2
info:
    description: Simple instant messaging application
    version: 2.0.0
    title: Simply Chat
    contact:
        email: biral.mattia@gmail.com
    license:
        name: GPL-3.0
        url: https://www.gnu.org/licenses/gpl-3.0.en.html
tags:
    - name: temp-users
      description: Handles registration and confirmation requests
components:
    securitySchemes:
        cookieAuth:
            type: apiKey
            in: cookie
            name: token
    schemas:
        username:
            type: string
            example: Pyrix25633
            minLength: 3
            maxLength: 32
        email:
            type: string
            format: email
            example: name.surname@domain.com
        password:
            type: string
            example: passwd1234@
paths:
    /register-username-feedback:
        get:
            tags:
                - temp-users
            summary: Username feedback for the registration form
            description: Returns a user friendly username feedback
            operationId: register-username-feedback
            parameters:
              - in: query
                name: username
                schema:
                    $ref: "#/components/schemas/username"
                description: The username, it can be invalid
                required: true
            responses:
                "200":
                    description: Username feedback
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    feedback:
                                        type: string
                                        example: Valid Username
    /register-email-feedback:
        get:
            tags:
                - temp-users
            summary: Email feedback for the registration form
            description: Returns a user friendly email feedback
            operationId: register-email-feedback
            parameters:
              - in: query
                name: email
                schema:
                    $ref: "#/components/schemas/email"
                description: The email, it can be invalid
                required: true
            responses:
                "200":
                    description: Email feedback
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    feedback:
                                        type: string
                                        example: Valid Email
    /temp-users:
        post:
            tags:
                - temp-users
            summary: Adds a new temporary user
            description: First step of the registration process
            operationId: temp-users
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                username:
                                    $ref: "#/components/schemas/username"
                                email:
                                    $ref: "#/components/schemas/email"
                                password:
                                    $ref: "#/components/schemas/password"
            responses:
                "201":
                    description: The first step of the registration succeded
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    username:
                                        $ref: "#/components/schemas/username"
                "400":
                    description: Bad Request
                "422":
                    description: "Unprocessable Content: Temporary user cannot be created because of duplicate username or email"
    /confirm-username-feedback:
        get:
            tags:
                - temp-users
            summary: Username feedback for the confirmation form
            description: Returns a user friendly username feedback
            operationId: confirm-username-feedback
            parameters:
              - in: query
                name: username
                schema:
                    $ref: "#/components/schemas/username"
                description: The username
                required: true
            responses:
                "200":
                    description: Username feedback
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    feedback:
                                        type: string
                                        example: Valid Username
                "400":
                    description: Bad Request
    /temp-users/{username}/confirm:
        post:
            tags:
                - temp-users
            summary: Confirms a temporary user
            description: Sencond and last step of the registration process
            operationId: temp-users/[username]/confirm
            parameters:
              - in: path
                name: username
                schema:
                    $ref: "#/components/schemas/username"
                required: true
            requestBody:
                content:
                    application/json:
                        schema:
                            type: object
                            properties:
                                verificationCode:
                                    type: integer
                                    minimum: 100000
                                    maximum: 999999
                                    example: 190347
            responses:
                "201":
                    description: The second step of the registration succeded, user created
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    userId:
                                        type: integer
                                        example: 10
                "400":
                    description: Bad Request
                "422":
                    description: "Unprocessable Content: User cannot be created"

servers:
    - url: https://simplychat.ddns.net/api/